<?php
// STRICT reporting: any query/prepare error throws an exception instead of
// silently returning false and causing a blank white page / fatal error
// further down the script.
mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);

set_exception_handler(function (Throwable $e) {
    http_response_code(500);
    error_log($e->getMessage());
    echo '<!DOCTYPE html><html lang="th"><head><meta charset="utf-8">'
       . '<title>เกิดข้อผิดพลาด</title></head><body style="font-family:sans-serif;padding:2rem">'
       . '<h2>เกิดข้อผิดพลาดของระบบ</h2>'
       . '<p>' . htmlspecialchars($e->getMessage()) . '</p></body></html>';
    exit;
});

try {
    $conn = new mysqli(
        'sql304.infinityfree.com',
        'if0_42862873',
        'QW8bnc5Nrr',
        'if0_42862873_workshop'
    );
} catch (mysqli_sql_exception $e) {
    http_response_code(500);
    die('ไม่สามารถเชื่อมต่อฐานข้อมูลได้: ' . htmlspecialchars($e->getMessage()));
}

$conn->set_charset('utf8mb4');
date_default_timezone_set('Asia/Bangkok');

// --- Auto-import: if the `admin` table doesn't exist yet (fresh database,
// work_shop.sql never imported through phpMyAdmin), import it automatically
// on the very first request so the site works without any manual step. ---
$tableCheck = $conn->query("SHOW TABLES LIKE 'admin'");
if ($tableCheck && $tableCheck->num_rows === 0) {
    $sqlFile = __DIR__ . '/../work_shop.sql';
    if (is_file($sqlFile)) {
        $sql = file_get_contents($sqlFile);
        // Strip comment lines so multi_query doesn't choke on them.
        $sql = preg_replace('/^--.*$/m', '', $sql);
        try {
            if ($conn->multi_query($sql)) {
                do {
                    // flush every result set generated by the dump
                } while ($conn->more_results() && $conn->next_result());
            }
        } catch (mysqli_sql_exception $e) {
            http_response_code(500);
            die(
                'ไม่สามารถนำเข้าฐานข้อมูลอัตโนมัติได้: ' . htmlspecialchars($e->getMessage())
                . '<br>กรุณานำเข้าไฟล์ work_shop.sql ผ่าน phpMyAdmin ด้วยตนเอง'
            );
        }
    }
}

// --- Auto-sync: keep the `test` superadmin's display name matched to the
// project's current seed data, so re-uploading this fix updates the live
// database automatically without a manual phpMyAdmin edit. ---
try {
    $conn->query(
        "UPDATE `admin` SET `first_name` = 'weeraphat', `last_name` = '' "
        . "WHERE `username` = 'test' AND (`first_name` != 'weeraphat' OR `last_name` != '')"
    );
} catch (mysqli_sql_exception $e) {
    // Non-critical: ignore if it fails, the rest of the site still works.
}